### ISSUE TITLE
Overlay for Anthos deployment

### ISSUE THREAD

**Issue by williamsmt** [GoogleCloudPlatform/gke-poc-toolkit-demos#5]
Deploying the central-cluster (along with ArgoCD) to an Anthos platform requires additional configuration for mounting the KSA secret into the deployment. We should consider creating a separate overlay to deploy to Anthos clusters.

Example patch:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/run/secrets/tokens/gcp-ksa/google-application-credentials.json
        name: argocd-server
        volumeMounts:
        - mountPath: /var/run/secrets/tokens/gcp-ksa
          name: gcp-ksa
          readOnly: true
      volumes:
      - name: gcp-ksa
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: $PROJECT_ID.svc.id.goog
              expirationSeconds: 172800
              path: token
          - configMap:
              items:
              - key: config
                path: google-application-credentials.json
              name: my-cloudsdk-config
              optional: false
```
